### ISSUE TITLE
running example assertion error

### ISSUE THREAD

**Issue by sphaero** [thedmd/imgui-node-editor#14]
Running latest master on Debian Buster errors:
```
gdb 00-Simple 
GNU gdb (Debian 7.12-6+b2) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from 00-Simple...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/arnaud/src/imgui-node-editor/Build/Bin/00-Simple 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0de7700 (LWP 21682)]
00-Simple: /home/arnaud/src/imgui-node-editor/NodeEditor/Source/Editor.h:69: ax::NodeEditor::NodeId ax::NodeEditor::Detail::ObjectId::AsNodeId() const: Assertion `IsNodeId()' failed.

Thread 1 "00-Simple" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6a7b231 in __GI_abort () at abort.c:79
#2  0x00007ffff6a729da in __assert_fail_base (fmt=0x7ffff6bc5d48 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x555555638f88 "IsNodeId()", 
    file=file@entry=0x555555638f40 "/home/arnaud/src/imgui-node-editor/NodeEditor/Source/Editor.h", 
    line=line@entry=69, 
    function=function@entry=0x555555639d80 <ax::NodeEditor::Detail::ObjectId::AsNodeId() const::__PRETTY_FUNCTION__> "ax::NodeEditor::NodeId ax::NodeEditor::Detail::ObjectId::AsNodeId() const") at assert.c:92
#3  0x00007ffff6a72a52 in __GI___assert_fail (assertion=0x555555638f88 "IsNodeId()", 
    file=0x555555638f40 "/home/arnaud/src/imgui-node-editor/NodeEditor/Source/Editor.h", line=69, 
    function=0x555555639d80 <ax::NodeEditor::Detail::ObjectId::AsNodeId() const::__PRETTY_FUNCTION__> "ax::NodeEditor::NodeId ax::NodeEditor::Detail::ObjectId::AsNodeId() const") at assert.c:101
#4  0x00005555555e78e1 in ax::NodeEditor::Detail::ObjectId::AsNodeId() const ()
#5  0x00005555555d4ffc in ax::NodeEditor::Detail::Settings::Parse(char const*, char const*, ax::NodeEditor::Detail::Settings&) ()
#6  0x00005555555e8378 in ax::NodeEditor::Detail::Settings::Parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ax::NodeEditor::Detail::Settings&) ()
#7  0x00005555555d0ff7 in ax::NodeEditor::Detail::EditorContext::LoadSettings() ()
#8  0x00005555555cd74d in ax::NodeEditor::Detail::EditorContext::Begin(char const*, ImVec2 const&) ()
#9  0x00005555555c6d05 in ax::NodeEditor::Begin(char const*, ImVec2 const&) ()
#10 0x000055555555b15a in Application_Frame() ()
#11 0x0000555555625be7 in main ()
```
Cmake did give a warning about OpenGL but I don't think it matters:
```
make
CMake Warning (dev) at /usr/share/cmake-3.11/Modules/FindOpenGL.cmake:270 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  Examples/Common/Application/CMakeLists.txt:14 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by thedmd** [comment]
@sphaero Hello. Thank you for reporting.

I fixed this issue some time ago, hope it still help.
